# Generated by Django 4.0.6 on 2022-07-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Фото')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('soname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Биография')),
                ('published', models.CharField(max_length=50, verbose_name='Материалы на сайте')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Автор_ки',
                'ordering': ['-soname'],
            },
        ),
    ]
