# Generated by Django 4.0.6 on 2022-08-06 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='published',
        ),
    ]
