# Generated by Django 4.0.6 on 2022-08-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_alter_authors_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='photo',
            field=models.ImageField(upload_to='mag/static/mag/images/', verbose_name='Фото'),
        ),
    ]
