# Generated by Django 4.0.6 on 2022-07-21 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название номера')),
                ('anotation_head', models.CharField(max_length=50, verbose_name='Заголовок аннотации')),
                ('anotation', models.TextField(blank=True, null=True, verbose_name='Аннотация')),
                ('published', models.CharField(max_length=50, verbose_name='выпуск (месяц//год)')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Оглавление материала')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('auth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='authors.authors', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anotation', models.TextField(blank=True, null=True, verbose_name='Аннотация')),
                ('spell', models.CharField(max_length=50, verbose_name='Порядоковый номер блока(цифрой)')),
                ('name', models.CharField(max_length=50, verbose_name='Название блока')),
                ('number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mag.number', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
                'ordering': ['-spell'],
            },
        ),
    ]
