# Generated by Django 4.0.6 on 2022-07-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
