# Generated by Django 4.0.6 on 2022-07-23 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0003_number_published_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mag.block', verbose_name='Блок'),
        ),
    ]
