# Generated by Django 4.0.6 on 2022-07-23 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0005_alter_material_options_material_spell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='number', to='mag.number', verbose_name='Номер'),
        ),
    ]
