# Generated by Django 4.0.6 on 2022-07-23 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0006_alter_block_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='block', to='mag.block', verbose_name='Блок'),
        ),
    ]
