# Generated by Django 4.0.6 on 2022-07-23 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0007_alter_material_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='number',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, related_name='numberr', to='mag.number', verbose_name='Номер'),
            preserve_default=False,
        ),
    ]
