# Generated by Django 4.0.6 on 2022-08-08 15:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0008_material_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='anotation',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Аннотация'),
        ),
        migrations.AlterField(
            model_name='material',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='number',
            name='anotation',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Аннотация'),
        ),
    ]
