# Generated by Django 4.0.6 on 2022-08-13 12:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0009_alter_block_anotation_alter_material_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
