# Generated by Django 4.0.6 on 2022-08-13 13:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0010_material_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='body',
        ),
        migrations.AddField(
            model_name='material',
            name='video',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Видео'),
        ),
    ]
