# Generated by Django 4.0.6 on 2022-08-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0012_material_video2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='video',
        ),
    ]
