# Generated by Django 4.0.6 on 2022-08-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0013_remove_material_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='musics/', verbose_name='Аудио'),
        ),
    ]
